### ISSUE TITLE
Shadcn needs components.json file

### ISSUE THREAD

**Issue by symaticvisuals** [joschan21/breadit#12]
`Configuration is missing. Please run init to create a components.json file.`

**Comment by Jolonauh** [comment]
You can just copy the files of the components you need from the ui folder from this repo into your own project.

**Comment by ujjwal-45** [comment]
Run this command : npx shadcn-ui init and then configure the files.

**Comment by joschan21** [comment]
> Run this command : npx shadcn-ui init and then configure the files.

Thanks for the answer, closing the issue :)
